FROM ubuntu:bionic

# to build this container:
# docker build -t image_saver -f Dockerfile.opencv-mqtt-image-save
# to run this container:
# docker run -ti image_saver python mqtt_sub_save.py

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libopencv-dev \
    mosquitto \
    mosquitto-clients \
    python-opencv \
    python-pip

RUN pip install paho-mqtt

WORKDIR /
COPY mqtt_sub_save.py .
