FROM python:3.7-alpine
LABEL Maintainer="Katayoun Borojerdi <kborojerdi@ischool.berkeley.edu" \
      Description="Mosquitto MQTT server based on Alpine Linux with Python. \
                  Includes Eclipse Paho MQTT Python client library."

RUN apk update && apk upgrade
RUN apk add mosquitto mosquitto-clients
RUN pip install paho-mqtt

WORKDIR /
COPY mqtt_forwarder.py .

# Expose MQTT port
EXPOSE 1883
